---
no-trailing-punctuation: false
no-inline-html: false
first-line-heading: false
link-fragments: false
table-column-style: false

# MD001 - Heading levels incrementing by one level
heading-increment: false

# MD013 - Line length
MD013:
  code_block_line_length: 80
  code_blocks: true
  heading_line_length: 80
  headings: true
  line_length: 130
  stern: true
  strict: false
  tables: false
